### PR TITLE
ndndpdk-depends.sh: minor fixes and improvements

### PR DESCRIPTION
**Pull request by Pesa**

### CODE REVIEW

**Comment by Pesa** [comment]
wrt `github_resolve_commit`, I wasn't sure why it's needed in the first place. Github's download URLs should work whether you use a commit SHA, a tag name, or "HEAD".

**Review by yoursunny — COMMENTED** [review]
The seemingly repeated `github_resolve_commit` are there because the first invocation may be skipped when `jq` is not installed, but the second invocation is expected to succeed.
If you want to delete the second invocation, add `jq` to NEEDED_BINARIES.

> I wasn't sure why it's needed in the first place. Github's download URLs should work whether you use a commit SHA, a tag name, or "HEAD".

I'd like to precisely record the version, i.e. have it displayed on Docker build logs.

**Comment by Pesa** [comment]
you clearly like to needlessly complicate simple matters...

**Review by yoursunny — APPROVED** [review]
Tested on Debian 11.

**Pull request merged**
